[theme]
# Default base theme is dark
base="dark"
backgroundColor="#352F44"
secondaryBackgroundColor="#5C5470"
primaryColor="#00c098"
textColor="#E5E4E8"
font="sans serif"
# Set the maximum file upload size to 500 megabytes
[server]
maxUploadSize = 200